Repository nikkuu19/Code-solutions, pull requests merged in 2022-10, with the labels that each got.

#2 added code in c++ to add two numbers
  Solutions-C++/addTwoNumbers.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 added code for linear search in C++
  Solutions-C++/linearSearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#5 added code for factorial in c++
  Solutions-C++/factorial.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#7 added code for computing palindrome of a number
  Solutions-C++/palindrome.cpp
Labels: hacktoberfest

#12 added code to get the dataTypeSize in c++.
  Solutions-C++/dataTypeSize.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#9 added code to get the current system time.
  Solutions-C++/currentTime.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#11 added code to swap two nums in c++.
  Solutions-C++/swapTwoNums.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#10 added code to compute volume of cube.
  Solutions-C++/volumeCube.cpp
Labels: good first issue, hacktoberfest

#13 Added explanation for Wiggle sequence problem
  462. Minimum Moves to Equal Array Elements II.md
  Solutions-C++/376. Wiggle Subsequence.md
Labels: hacktoberfest, hacktoberfest-accepted

#16 Awarness
  2327. Number of People Aware of a Secret.md
Labels: hacktoberfest, hacktoberfest-accepted

#17 2328. Number of Increasing Paths in a Grid added
  2328. Number of Increasing Paths in a Grid.md
Labels: hacktoberfest, hacktoberfest-accepted

#18 repo restructuring
  Solutions-C++/2327. Number of People Aware of a Secret.md
  Solutions-C++/2328. Number of Increasing Paths in a Grid.md
  Solutions-C++/462. Minimum Moves to Equal Array Elements II.md
  Solutions-C++/718. Maximum Length of Repeated Subarray.md
Labels: hacktoberfest, hacktoberfest-accepted

#19 Added BFS and DFS code
  breadth_first_search.cpp
  depth_first_search.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 add: cpp code for problem
  42. Trapping Rain Water.md
Labels: hacktoberfest, hacktoberfest-accepted

#21 add: code for n queens 2
  52. N-Queens II.md
Labels: hacktoberfest, hacktoberfest-accepted

#22 add: code for unique bst
  96. Unique Binary Search Trees.md
Labels: hacktoberfest, hacktoberfest-accepted

#23 add: code for house robber cpp
  198. House Robber.md
Labels: hacktoberfest, hacktoberfest-accepted

#24 Create 2136. Earliest Possible Day of Full Bloom.cpp
  Solutions-C++/2136. Earliest Possible Day of Full Bloom.cpp
Labels: hacktoberfest, hacktoberfest-accepted
